import "./globals.css";
import { Audiowide, Poppins } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const audiowide = Audiowide({
  subsets: ["latin"],
  weight: "400", // Audiowide only supports weight 400
  variable: "--font-audiowide", // Optional: for Tailwind CSS
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className={`${audiowide.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
